[package]
name = "ytdlrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
rfd = "0.15.0"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.7.2"
