[package]
name = "ytdlrs"
version = "0.1.0"
edition = "2021"

[dependencies]
flexi_logger = "0.29.6"
log = "0.4.22"
rfd = "0.15.0"
slint = "1.8.0"
tokio = { version = "1.41.1", features = ["full"] }

[build-dependencies]
slint-build = "1.7.2"
